app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
]

polls/urls.py
from django.urls import path
from . import views as polls_views


app_name = 'polls'


urlpatterns = [
    path('', polls_views.index, name = "index"),
    #ex: /polls/5/
    path('<int:question_id>/', polls_views.detail, name = "detail"),
    #ex /polls/5/results
    path('<int:question_id>/results', polls_views.result, name = "results"),
    #path /polls/5/vote
    path('<int:question_id>/vote', polls_views.vote, name = "vote"),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    #metodo per capire se una domanda è stata posta prima
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]   #gli ultimi 5
    #output = ','.join([q.question_text for q in latest_question_list])
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    #return HttpResponse("Hi there, It's working")
    #return HttpResponse(template.render(context, request))
    #render(Arg[0] = request, arg[1] = template name, arg[2] = context)
    return render(request, 'polls/index.html', context) 

def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk = question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question doesn't exist")

    question = get_object_or_404(Question, pk = question_id)
    
    return render(request, 'polls/detail.html', {'question': question})


def result(request, question_id):
    response = "You are looking at the result of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You are voting on question %s." % question_id)

polls/templates/polls/detail.html
<h1>{{ queston.question_text }}</h1>

{% if error_message %}
    <p><strong> {{error_message}} </strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choise_text }}</label>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INDEX</title>
</head>
<body>
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>